add_newline = false

right_format =  " $python "
# Replace the "â¯"
[character]
success_symbol = "[Î»](green)"
error_symbol = "[Î»](red)"

[directory]
truncation_length = 4
truncate_to_repo = true
style = "blue"
read_only = " ğŸ”’"
read_only_style = "fg:#ffb86c"
truncation_symbol = "â‹¯"
home_symbol = "~"
format = "[$path]($style)[$read_only]($read_only_style) "

[docker_context]
format = "via [ğŸ‹ $context](blue bold)"

[git_status]
conflicted = " ~ "
ahead = " â‡¡ ${count}"
behind = " â‡£ ${count}"
staged = '[+\($count\)](yellow)'
diverged = " â‡• â‡¡ ${ahead_count} â‡£ ${behind_count}"
untracked = " ? "
stashed = " $ "
modified = " ! "
deleted = " ïš¿ "
renamed = " Â» "
up_to_date = " "
style = "bold white"
format = "[$all_status]($style)"

[git_branch]
symbol = "î‚  "
truncation_length = 12
truncation_symbol = "â‹¯"
only_attached = false
#style = "bold purple"
format = " [$symbol$branch]($style) "
# symbol = "ğŸŒ± "
style = "bold yellow"

[git_commit]
commit_hash_length = 8
style = "bold white"

[hg_branch]
symbol = "ï˜ "
style =	"bold purple"
format = "on [$symbol$branch]($style) "

[python]
format = " [$symbol$version]($style) "
# format='[${symbol}${pyenv_prefix}( \($virtualenv\))]($style)'
pyenv_version_name = true
style = "bold green"
# version_format = "raw"