add_newline = false

right_format =  " $python "
# Replace the "â¯"
[character]
success_symbol = "[Î»](green)"
error_symbol = "[Î»](red)"

[cmd_duration]
disabled = true

[directory]
truncation_length = 4
truncate_to_repo = true
style = "blue"
read_only = " ï ½"
read_only_style = "fg:#ffb86c"
truncation_symbol = "â‹¯"
home_symbol = "~"
format = "[$path]($style)[$read_only]($read_only_style) "

[docker_context]
format = "via [ğŸ‹ $context](blue bold)"
symbol = "ïŒˆ "

[aws]
symbol = "îŒ½  "
format = "on [$symbol$region]($style) "
style = "bold blue"

[conda]
symbol = "ï„Œ "

[dart]
symbol = "î˜ "

[elixir]
symbol = "î‰µ "

[elm]
symbol = "î˜¬ "

# [git_status]
# conflicted = " ~ "
# ahead = " â‡¡ ${count}"
# behind = " â‡£ ${count}"
# staged = '[+\($count\)](yellow)'
# diverged = " â‡• â‡¡ ${ahead_count} â‡£ ${behind_count}"
# untracked = " ? "
# stashed = " $ "
# modified = " ! "
# deleted = " ïš¿ "
# renamed = " Â» "
# up_to_date = " "
# style = "bold white"
# format = "[$all_status]($style)"
# # format = '([\[$all_status$ahead_behind\]]($style))'

[git_status]
format = '([$conflicted$deleted$renamed$modified$staged$untracked$ahead_behind]($style) )'
ahead = "[â‡¡${count}](7)"
diverged = "[â‡•â‡¡${ahead_count}â‡£${behind_count}](7)"
behind = "[â‡£${count}](7)"
modified = "[!](red)"
deleted = "[x](red)"
untracked = "[?](yellow)"
staged = "[+](yellow)"
renamed = ""
style = "green"

[git_branch]
# symbol = "î‚  "
truncation_length = 12
truncation_symbol = "â‹¯ "
only_attached = false
format = "on [$symbol$branch]($style) "
symbol = "ï˜ "
style = "bold yellow"

[git_commit]
commit_hash_length = 8
style = "bold white"

[golang]
symbol = "î˜§ "

[hg_branch]
symbol = "ï˜ "
style =	"bold purple"
format = "on [$symbol$branch]($style) "

[java]
symbol = "î‰– "

[julia]
symbol = "î˜¤ "

[memory_usage]
symbol = "ï¡š "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ï‹œ "

[package]
symbol = "ï£– "

[perl]
symbol = "î© "

[php]
symbol = "î˜ˆ "

[python]
format = " [$symbol$version]($style) "
pyenv_version_name = true
style = "bright-black"
symbol = "î˜† "

[ruby]
symbol = "îˆ¾ "

[rust]
symbol = "î¨ "

[scala]
symbol = "îœ· "

[shlvl]
symbol = "ï„  "

[swift]
symbol = "ï¯£ "
